### ISSUE TITLE
Prevent wrong timing in execution due to js' single threaded nature

### ISSUE THREAD

**Issue by graciano** [tananamusic/tanana#15]
So, `js` is sort of `single-threaded`* and timers are not guaranteed to respect the time. So, for the music to be played the right way, it'll need a refresher, like the code below, from the [atom-clock](https://github.com/b3by/atom-clock) source.
```javascript
startTicker() {
    this.setDate()
    var nextTick = this.refreshInterval - (Date.now() % this.refreshInterval)
    this.tick = setTimeout (() =>  { this.startTicker() }, nextTick)
  }
```

Since #1 is already taking too long to be finished, I'll make this in a separate issue.

*: [Here](http://ejohn.org/blog/how-javascript-timers-work/) and [here](http://stackoverflow.com/questions/2734025/is-javascript-guaranteed-to-be-single-threaded) are some references for this single threaded stuff.

**Comment by HeavenVolkoff** [comment]
Use [`requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) as foundation to construct the Refresher.
